[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = false
  AddthisId = "your AddthisId"

[Comment]
  Enable = false
  Module = "Waline"
  LiveReId = "Your LiveReId"
  WalineSerURL = "Your WalineSerURL"

  # If Module is "Utterances",see https://utteranc.es/
  UtterancesRepo = "owner/repo"
  UtterancesTheme = "github-light"
  UtterancesTitle = "pathname"

[LeanCloud]
  AppId = "Your LCAppId"
  AppKey = "Your LCAppKey"
  ServerURL = "Your LCServer"

[Statis]
  BusuanziCounter = true
#  CNNZSiteId = "Your CNNZSiteId"
  BaiduSiteId = "e81c4027dd454fce2c17467758558b66"
#  GoogleSiteId = "Your GoogleSiteId"
#  LaSiteId = "Your LaSiteId"

[OnlineIM]
  Enable = false
#  DaoVoiceId = "Your DaoVoiceId"

[Others]
#  RevolverMapId = "Your RevolverMapId"