name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: prod
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: List Submodules
        run: echo | ls ./themes

      - name: List PWD
        run: echo | ls ./

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Set Hugo Share Configuration
        env:
          HUGO_ADDTHIS_ID: ${{ secrets.HUGO_ADD_THIS_ID }}
        run: |
          mkdir -p ./config/production
          echo -e "[Share]\n  Enable = true\n  AddthisId = \"${HUGO_ADDTHIS_ID}\"" > ./config/production/params.toml
          echo 'ok'
        working-directory: ./

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public